#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVACMD="java"
JVM_OPTS=$DEFAULT_JVM_OPTS

exec "$JAVACMD" $JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
